import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  Topbar,
  TopbarBtn,
  TopbarTypography,
} from "../components/styled-components/Topbar";
import { Body } from "../components/styled-components/Body";
import Navbar from "../page-components/home-page/Navbar";
import Banner from "../page-components/home-page/Banner";
import Section1 from "../page-components/home-page/New-arivals";
import Section2 from "../page-components/home-page/Special-offers";
import Section3 from "../page-components/home-page/Shop-by-Categories";
import Newsletter from "../page-components/home-page/Newsletter";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Topbar>
          <TopbarTypography>
            Buy now and get it in 2 hours or less. Dont miss out
          </TopbarTypography>
          <TopbarBtn>Shop Now</TopbarBtn>
        </Topbar>
        <Navbar />
        <Banner />
        <Body>
          <Section1 />
          <Section2 />
          <Section3 />
        </Body>
      </main>
      <footer>
        <Newsletter />
      </footer>
    </div>
  );
};

export default Home;
